[package]
name = "mkey"
version = "0.2.0"
edition = "2024"
authors = ["Mạnh Kiên <manhkien13041997@gmail.com>"]
description = "MKey - Bộ gõ tiếng Việt siêu nhẹ, hiệu năng cao viết bằng Rust"
default-run = "MKey"

[lib]
name = "mkey"
path = "src/lib.rs"

[[bin]]
name = "MKey"
path = "src/main.rs"

[[example]]
name = "combinatorial_tester"
path = "examples/combinatorial_tester.rs"

[dependencies]

[build-dependencies]
winres = "0.1.12"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
